/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>

/* This function executes in THREAD MODE of the processor */
int main(void)
{
  /* 1. Enable all configurable system exceptions:
    Usage Fault, Mem manage fault and Bus fault */
  uint32_t *pSHCSR = (uint32_t *)0xE000ED24;
  *pSHCSR |= (1 << 16); /* Mem manage Fault */
  *pSHCSR |= (1 << 17); /* Bus Fault */
  *pSHCSR |= (1 << 18); /* Usage Fault */

  /* 2. Lets force the processor to execute SVC exception */
  __asm volatile ("SVC #25");
  uint32_t data = 0;

  __asm volatile ("MOV %0, R0": "=r"(data) ::);
  printf("data = %ld\n", data);

	for(;;);
}

/* 2. implement the SVC handlers */

__attribute__ ((naked)) void SVC_Handler(void)
{
	//here we extracted the value of MSP which happens to be the
	//base address of the stack frame(thread mode) which got saved during the exception entry
	//from thread mode to handler mode
	__asm ("MRS r0,MSP");
	__asm ("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t *pBaseStackFrame)
{
	printf("Extract Return Address(PC) = %ld\n", pBaseStackFrame[6]);
  uint8_t *pReturn_addr = (uint8_t *)pBaseStackFrame[6];
  /* Decrement thereturn address by 2 to point to opcode of the SVC 
     instruction in the program memory */
  pReturn_addr = pReturn_addr-2;
  /* Extract the SVC number */
  uint8_t svc_number = *pReturn_addr;
	printf("Value of svc_number = %d\n", svc_number);
  svc_number+=4;
  /* Update register r0 as return value from SVC handler */
  pBaseStackFrame[0] = svc_number;
}
